name: Build MicroPython

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout MicroPython
      run: git clone --recurse-submodules https://github.com/micropython/micropython.git

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libffi-dev git pkg-config \
            libssl-dev python3 python3-pip python3-venv
        sudo apt-get install -y gcc-arm-none-eabi
        
    - name: Configure CMake
      run: |
        cd micropython/ports/rp2
        mkdir build
        cd build
        cmake -DPICO_TOOLCHAIN_PATH=/usr/bin ..

    - name: Build MicroPython for RP2040
      run: |
        cd micropython
        make -C mpy-cross
        cd ports/rp2
        make submodules
        make

    - name: Use Secret LINDA
      run: echo "El valor de LINDA es $LINDA"
      env:
        LINDA: ${{ secrets.LINDA }}

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0
        name: "MicroPython Release"
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ github.token }}
